.\#
.\# gcbayes.1
.\# gcbayes Manual Page
.\#
.\# Created by Jayanth Chennamangalam
.\#

.TH GCBAYES 1 "2012-08-06" "GCBAYES 1.0" \
"BAYESIAN ANALYSIS OF GLOBULAR CLUSTER PULSARS"


.SH NAME
gcbayes \- perform a Bayesian analysis of globular cluster pulsar luminosities


.SH SYNOPSIS
.B gcbayes
[options]


.SH DESCRIPTION
Perform a Bayesian analysis of globular cluster pulsar luminosities.


.SH OPTIONS
.TP
\-h  --help
display a short help text
.TP
\-N  --n-min <value>
minimum N (default is 0)
.TP
\-S  --n-step <value>
step size in N  (default is 1)
.TP
\-X  --n-max <value>
maximum N (default is 1000)
.TP
\-m  --mean-min <value>
minimum mean (<log S>) (default is -1.19)
.TP
\-p  --mean-step <value>
mean (<log L>) step size (default is 0.01)
.TP
\-u  --mean-max <value>
maximum mean (<log L>) (default is -1.04)
.TP
\-s  --sd-min <value>
minimum standard deviation (of log L) (default is 0.91)
.TP
\-e  --sd-step <value>
standard deviation (of log L) step size (default is 0.01)
.TP
\-a  --sd-max <value>
maximum standard deviation (of log L) (default is 0.98)
.TP
\-l  --s-min-min <value>
minimum flux in mJy (default is 0.001)
.TP
\-t  --s-min-step <value>
flux step size in mJy (default is 0.001)
.TP
\-y  --conf-file <filename>
config file
.TP
\-c  --colour-map <name>
name of colour map
.TP
\-f  --plot-ps
print to PS file, instead of screen
.TP
\-z  --plot-all
plot both S and L posteriors
.TP
\-w  --plot-lall
plot all marginalised posteriors for L

.SH FILES
.TP
run/<GC-config>.gc
The globular cluster configuration file.
.TP
run/<GC-flux>
The globular cluster pulsar flux list.


.SH EXAMPLE
gcbayes -N 25 -S 1 -X 500 -m -2.0 -p 0.05 -u 0.5 -s 0.2 -e 0.01 -a 1.4 -y ter5_wide.gc -w


.SH SEE ALSO
.I Chennamangalam, Lorimer, Mandel, Bagchi, 2012, Submitted to MNRAS


.SH AUTHORS
.TP 
gcbayes was written by Jayanth Chennamangalam with inputs from Duncan \
Lorimer, Ilya Mandel, and Manjari Bagchi.

